name: admin-CI

on:
  push:
    paths:
      - 'backend/application/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'backend/application/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
        env:
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          CLOUDINARY_API_KEY:
          CLOUDINARY_CLOUD_NAME:
          CLOUDINARY_POSTFIX:
          CLOUDINARY_API_SECRET:
